# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent Cloud.

[tool.black]
target_version = ['py38']
line-length = 99
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
)/
'''

[tool.isort]
py_version = 38
line_length = 99
multi_line_output = 3
include_trailing_comma = true
profile = 'black'
skip_gitignore = true
